In [1]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
train=pd.read_csv("spaceship-titanic/train.csv")

In [35]:
train.sample()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
6689,7056_01,Europa,False,D/217/S,55 Cancri e,43.0,False,0.0,2093.0,0.0,3409.0,30.0,Alramix Secont,False

In [32]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   str
 1   HomePlanet    8693 non-null   str
 2   CryoSleep     8693 non-null   object
 3   Cabin         8693 non-null   str
 4   Destination   8693 non-null   str
 5   Age           8693 non-null   float64
 6   VIP           8693 non-null   object
 7   RoomService   8693 non-null   float64
 8   FoodCourt     8693 non-null   float64
 9   ShoppingMall  8693 non-null   float64
 10  Spa           8693 non-null   float64
 11  VRDeck        8693 non-null   float64
 12  Name          8693 non-null   str
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(2), str(5)
memory usage: 891.5+ KB

In [31]:
train.isnull().sum()

PassengerId     0
HomePlanet      0
CryoSleep       0
Cabin           0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
Name            0
Transported     0
dtype: int64

In [30]:
(train.isnull().sum() / len(train)) * 100

PassengerId     0.0
HomePlanet      0.0
CryoSleep       0.0
Cabin           0.0
Destination     0.0
Age             0.0
VIP             0.0
RoomService     0.0
FoodCourt       0.0
ShoppingMall    0.0
Spa             0.0
VRDeck          0.0
Name            0.0
Transported     0.0
dtype: float64

In [12]:
print(train["CryoSleep"].mode())
train["CryoSleep"]=train["CryoSleep"].fillna("False")

0    False
Name: CryoSleep, dtype: object

In [13]:
print(train["HomePlanet"].mode())
train["HomePlanet"]=train["HomePlanet"].fillna("Earth")

0    Earth
Name: HomePlanet, dtype: str

In [18]:
print(train["Cabin"].mode())
train["Cabin"]=train["Cabin"].fillna("G/734/S")

0    G/734/S
Name: Cabin, dtype: str

In [20]:
print(train["Destination"].mode())
train["Destination"]=train["Destination"].fillna("TRAPPIST-1e")

0    TRAPPIST-1e
Name: Destination, dtype: str

In [22]:
print(train["VIP"].mode())
train["VIP"]=train["VIP"].fillna("False")

0    False
Name: VIP, dtype: object

In [ ]:
# Numerical columns
# filled every null value of num or numerical columns at once 
# the fillna will find the mean of every train num columns 
num_cols = ['Age', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']
train[num_cols] = train[num_cols].fillna(train[num_cols].mean())

In [29]:
# to fill nan values of name 
train['Name']=train['Name'].fillna('Unknown')

In [39]:
# ENCORDING converying cat to num 
# We encode categorical text data into numbers because most machine learning algorithms can only work with numbers, not text.
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()

In [40]:
train.columns

Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age',
       'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck',
       'Name', 'Transported'],
      dtype='str')

In [53]:
for i in train.columns:
    if train[i].dtype=="str":
        train[i]=LE.fit_transform(train[i])
    else:
        print(i)

PassengerId
HomePlanet
CryoSleep
Cabin
Destination
Age
VIP
RoomService
FoodCourt
ShoppingMall
Spa
VRDeck
Name
Transported

In [54]:
train.sample()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
4415,4415,1,True,242,2,36,False,0,0,0,0,0,5421,True

In [57]:
print(train[["VIP", "CryoSleep"]].head())
print(train[["VIP", "CryoSleep"]].dtypes)

     VIP CryoSleep
0  False     False
1  False     False
2   True     False
3  False     False
4  False     False
VIP          object
CryoSleep    object
dtype: object